
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mssql+pyodbc://HBuck:KzgN819+@dist-6-505.uopnet.plymouth.ac.uk/COMP2001_HBuck?driver=ODBC+Driver+17+for+SQL+Server
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: